baseurl: ''
permalink: pretty
title: Intersecurity-Komposch
google_analytics_id: ''
homepage:
  show_call_box: true
logo:
  mobile: images/logo/logo-mobile.svg
  desktop: images/logo/logo.svg
  desktop_height: 36px
footer:
  copyright_text: >-
    Free Jekyll theme by <a class="zerostatic"
    href="https://www.zerostatic.io">www.zerostatic.io</a>
seo:
  meta_og_title: Intersecurity-Komposch
  meta_og_type: website
  meta_og_url: 'https://jekyll-serif.netlify.app'
  meta_og_image: >-
    https://raw.githubusercontent.com/zerostaticthemes/jekyll-serif-theme/master/screenshots/tn.png
  meta_og_description: >-
    Intersecurity-Komposch ist ein Sicherheits- und Detektivunternehmen mit Sitz
    in Kärnten. Wir kümmern uns um alle sicherheitsrelevanten Aufgaben von
    Bewachung bis zu Überwachung.
  meta_twitter_card: ''
  meta_twitter_site: ''
  meta_twitter_creator: ''
collections:
  services:
    output: true
  team:
    output: true
sass:
  indentWidth: 4
  style: compact
  precision: 10
plugins:
  - jekyll-environment-variables
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
url: ''
